# Optional nginx for secure upload
services:
  nginx:
    image: nginx:alpine
    depends_on:
      - cluster
    ports:
      - "5555:5555"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./htpasswd:/etc/nginx/.htpasswd:ro 