# Production overrides
services:
  ipfs:
    ports:
      - "4001:4001"  # swarm
      - "5001:5001"  # api
  nginx:
    ports:
      - "80:80"
      - "443:443"
      - "5555:5555"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./htpasswd:/etc/nginx/.htpasswd:ro
      - ./data/certbot/conf:/etc/letsencrypt
    environment:
      - DOMAIN=${DOMAIN} 