# Proxy mode overrides
services:
  ipfs:
    ports:
      - "4001:4001"  # swarm
      - "5001:5001"  # api
    labels:
      - "traefik.enable=true"
      
      # IPFS Gateway Service
      - "traefik.http.services.ipfs-gateway.loadbalancer.server.port=8080"
      
      # Main gateway router
      - "traefik.http.routers.main-gateway.rule=Host(`${GATEWAY_DOMAIN}`)"
      - "traefik.http.routers.main-gateway.entrypoints=web"
      - "traefik.http.routers.main-gateway.middlewares=ipfs-headers"
      - "traefik.http.routers.main-gateway.service=ipfs-gateway"
      
      # Subdomain gateway router
      - "traefik.http.routers.subdomain-gateway.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.ipfs.${GATEWAY_DOMAIN}`)"
      - "traefik.http.routers.subdomain-gateway.entrypoints=web"
      - "traefik.http.routers.subdomain-gateway.middlewares=ipfs-headers"
      - "traefik.http.routers.subdomain-gateway.service=ipfs-gateway"
      
      # Headers (same as nginx)
      - "traefik.http.middlewares.ipfs-headers.headers.customrequestheaders.Host=$${host}"
      - "traefik.http.middlewares.ipfs-headers.headers.customrequestheaders.X-Real-IP=$${remote_addr}"
      - "traefik.http.middlewares.ipfs-headers.headers.customrequestheaders.X-Forwarded-For=$${remote_addr}"
      - "traefik.http.middlewares.ipfs-headers.headers.customrequestheaders.X-Forwarded-Proto=$${scheme}"
      
      # Catch-all rule for 404s
      - "traefik.http.routers.catch-all.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.catch-all.priority=1"  # Lower priority than other rules
      - "traefik.http.routers.catch-all.middlewares=error-pages"
      - "traefik.http.middlewares.error-pages.errors.status=404"
      - "traefik.http.middlewares.error-pages.errors.service=error"
      - "traefik.http.middlewares.error-pages.errors.query=/{status}.html"

  cluster:
    labels:
      - "traefik.enable=true"
      
      # Upload Service
      - "traefik.http.services.upload-service.loadbalancer.server.port=9095"
      
      # Upload Router
      - "traefik.http.routers.upload-router.rule=Host(`${UPLOAD_DOMAIN}`) && PathPrefix(`/api/v0/`) && (Path(`/api/v0/add`) || Path(`/api/v0/cat`) || Path(`/api/v0/pin/ls`) || Path(`/api/v0/pin/add`))"
      - "traefik.http.routers.upload-router.entrypoints=web"
      - "traefik.http.routers.upload-router.middlewares=upload-auth,ipfs-headers"
      - "traefik.http.routers.upload-router.service=upload-service"
      
      # Upload Auth
      - "traefik.http.middlewares.upload-auth.basicauth.usersfile=/etc/traefik/.htpasswd"

  traefik:
    ports:
      - "80:80"     # HTTP (for Cloudflare proxy)
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      # Detailed access logging
      - "--accesslog.fields.headers.names=Host,X-Forwarded-For,X-Forwarded-Proto,Location"
      - "--accesslog.fields.defaultmode=keep"
      - "--accesslog.fields.names.RequestHost=keep"
      - "--accesslog.fields.names.RequestPath=keep"
      - "--accesslog.fields.names.RequestMethod=keep"
      - "--accesslog.fields.names.RequestProtocol=keep"
      - "--accesslog.fields.names.OriginStatus=keep"
      # Debug headers
      - "--entrypoints.web.transport.respondingTimeouts.readTimeout=0"
      - "--entrypoints.web.transport.respondingTimeouts.writeTimeout=0"
      - "--entrypoints.web.forwardedHeaders.insecure=true"
    environment:
      - GATEWAY_DOMAIN=${GATEWAY_DOMAIN}
      - UPLOAD_DOMAIN=${UPLOAD_DOMAIN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./htpasswd:/etc/traefik/.htpasswd:ro 