# DNS mode overrides
services:
  ipfs:
    labels:
      - "traefik.enable=true"
      
      # IPFS Gateway Service
      - "traefik.http.services.ipfs-gateway.loadbalancer.server.port=8080"
      
      # Main gateway router
      - "traefik.http.routers.main-gateway.rule=Host(`${GATEWAY_DOMAIN}`)"
      - "traefik.http.routers.main-gateway.entrypoints=web"
      - "traefik.http.routers.main-gateway.service=ipfs-gateway"
      
      # Subdomain gateway router
      - "traefik.http.routers.subdomain-gateway.rule=HostRegexp(`{subdomain:[^.]+}.ipfs.${GATEWAY_DOMAIN}`)"
      - "traefik.http.routers.subdomain-gateway.entrypoints=web"
      - "traefik.http.routers.subdomain-gateway.service=ipfs-gateway"

  cluster:
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.upload-service.loadbalancer.server.port=9095"
      - "traefik.http.routers.upload-router.rule=Host(`${UPLOAD_DOMAIN}`) && (Path(`/api/v0/add`) || Path(`/api/v0/cat`) || Path(`/api/v0/pin/ls`) || Path(`/api/v0/pin/add`))"
      - "traefik.http.routers.upload-router.entrypoints=web"
      - "traefik.http.routers.upload-router.middlewares=upload-auth"
      - "traefik.http.routers.upload-router.service=upload-service"

  traefik:
    ports:
      - "80:80"  # HTTP (for Cloudflare proxy)
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"
      - "--accesslog=true"