services:
  ipfs:
    container_name: ipfs
    image: ipfs/kubo:release
    ports:
      - "4001:4001"  # swarm
      - "8080:8080"  # gateway (IP mode only)
      - "5001:5001"  # api
    volumes:
      - ./data/ipfs:/data/ipfs
      - ./ipfs.config.json:/data/ipfs/config:ro
    environment:
      - IPFS_GATEWAY_PUBLICGATEWAYS_USESUBDOMAINS=true
    labels:
      - "traefik.enable=true"
      # IPFS routes
      - "traefik.http.routers.ipfs.rule=PathPrefix(`/ipfs/`) || PathPrefix(`/ipns/`)"
      - "traefik.http.routers.ipfs.entrypoints=web"
      - "traefik.http.services.ipfs.loadbalancer.server.port=8080"

  cluster:
    container_name: cluster
    image: ipfs/ipfs-cluster:${IPFS_CLUSTER_VERSION:-latest}
    depends_on:
      - ipfs
    environment:
      CLUSTER_PEERNAME: ${PEERNAME}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs/tcp/5001
      CLUSTER_IPFSHTTP_HTTPLISTENMULTIADDRESS: /ip4/ipfs/tcp/5001
      CLUSTER_IPFSPROXY_NODEMULTIADDRESS: /dns4/ipfs/tcp/5001
      CLUSTER_IPFSPROXY_LISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9095
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_SECRET: ${SECRET}
      CLUSTER_PEERADDRESSES: ${PEERADDRESSES}
    ports:
      - "9094:9094"
      - "9095:9095"
      - "9096:9096"
    volumes:
      - ./data/ipfs-cluster:/data/ipfs-cluster
      - ./service.json:/data/ipfs-cluster/service.json
      - ./identity.json:/data/ipfs-cluster/identity.json
    labels:
      - "traefik.enable=true"
      # IPFS Cluster routes
      - "traefik.http.routers.cluster.rule=Path(`/api/v0/add`) || Path(`/api/v0/cat`) || Path(`/api/v0/pin/ls`) || Path(`/api/v0/pin/add`)"
      - "traefik.http.routers.cluster.entrypoints=web"
      - "traefik.http.routers.cluster.middlewares=auth"
      - "traefik.http.services.cluster.loadbalancer.server.port=9095"
      - "traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/.htpasswd"

  traefik:
    image: traefik:v2.10
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:5555"
      - "--log.level=INFO"
    ports:
      - "5555:5555"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./htpasswd:/etc/traefik/.htpasswd:ro 